from io import BytesIO
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor, white, black
from reportlab.lib.units import cm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# Color palette
DEEP_PURPLE = HexColor("#0a0020")
DARK_PURPLE = HexColor("#1a0a3e")
MID_PURPLE = HexColor("#2d1b69")
GOLD = HexColor("#d4af37")
GOLD_LIGHT = HexColor("#f0d060")
SILVER = HexColor("#c0c0c0")
WHITE = HexColor("#ffffff")
LIGHT_GRAY = HexColor("#e8e0f0")


def _styles() -> dict:
    return {
        "title": ParagraphStyle(
            "Title",
            fontSize=28,
            textColor=GOLD,
            alignment=TA_CENTER,
            spaceAfter=6,
            fontName="Helvetica-Bold",
            leading=34,
        ),
        "subtitle": ParagraphStyle(
            "Subtitle",
            fontSize=12,
            textColor=SILVER,
            alignment=TA_CENTER,
            spaceAfter=4,
            fontName="Helvetica",
        ),
        "section_header": ParagraphStyle(
            "SectionHeader",
            fontSize=14,
            textColor=GOLD,
            spaceAfter=8,
            spaceBefore=16,
            fontName="Helvetica-Bold",
        ),
        "body": ParagraphStyle(
            "Body",
            fontSize=10,
            textColor=LIGHT_GRAY,
            spaceAfter=8,
            fontName="Helvetica",
            leading=16,
        ),
        "number_label": ParagraphStyle(
            "NumberLabel",
            fontSize=9,
            textColor=SILVER,
            alignment=TA_CENTER,
            fontName="Helvetica",
        ),
        "number_value": ParagraphStyle(
            "NumberValue",
            fontSize=22,
            textColor=GOLD,
            alignment=TA_CENTER,
            fontName="Helvetica-Bold",
        ),
        "footer": ParagraphStyle(
            "Footer",
            fontSize=8,
            textColor=SILVER,
            alignment=TA_CENTER,
            fontName="Helvetica",
        ),
    }


def _draw_background(canvas, doc):
    canvas.saveState()
    w, h = A4
    canvas.setFillColor(DEEP_PURPLE)
    canvas.rect(0, 0, w, h, fill=1, stroke=0)

    # Decorative header band
    canvas.setFillColor(DARK_PURPLE)
    canvas.rect(0, h - 3.5 * cm, w, 3.5 * cm, fill=1, stroke=0)

    # Gold top border line
    canvas.setStrokeColor(GOLD)
    canvas.setLineWidth(2)
    canvas.line(1 * cm, h - 3.5 * cm, w - 1 * cm, h - 3.5 * cm)

    # Gold bottom border line
    canvas.line(1 * cm, 1.5 * cm, w - 1 * cm, 1.5 * cm)

    # Footer text
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(SILVER)
    canvas.drawCentredString(
        w / 2,
        0.8 * cm,
        f"Generated by AI Numerology  •  {datetime.now().strftime('%B %d, %Y')}  •  Confidential Reading",
    )

    # Page number
    canvas.drawRightString(w - 1.5 * cm, 0.8 * cm, f"Page {doc.page}")
    canvas.restoreState()


def _number_table(numbers: dict, styles: dict) -> Table:
    """Create a 4-column grid of core numbers."""
    fields = [
        ("Life Path", numbers["life_path"]),
        ("Destiny", numbers["destiny"]),
        ("Soul Urge", numbers["soul_urge"]),
        ("Personality", numbers["personality"]),
        ("Birthday", numbers["birthday"]),
        ("Personal Year", numbers["personal_year"]),
        ("Expression", numbers["expression"]),
        ("Lucky Sum", numbers["lucky_numbers"][0] if numbers["lucky_numbers"] else "-"),
    ]

    cells = []
    row = []
    for i, (label, value) in enumerate(fields):
        cell = [
            Paragraph(str(value), styles["number_value"]),
            Paragraph(label, styles["number_label"]),
        ]
        row.append(cell)
        if (i + 1) % 4 == 0:
            cells.append(row)
            row = []
    if row:
        while len(row) < 4:
            row.append([""])
        cells.append(row)

    table = Table(cells, colWidths=[4.3 * cm] * 4, rowHeights=[2.5 * cm] * len(cells))
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), MID_PURPLE),
        ("GRID", (0, 0), (-1, -1), 0.5, GOLD),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("ROUNDEDCORNERS", [4]),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    return table


def _lucky_table(numbers: dict, styles: dict) -> Table:
    header = [
        Paragraph("🔢 Lucky Numbers", styles["section_header"]),
        Paragraph("🎨 Lucky Colors", styles["section_header"]),
        Paragraph("📅 Lucky Days", styles["section_header"]),
    ]
    values = [
        Paragraph(", ".join(str(n) for n in numbers["lucky_numbers"]), styles["body"]),
        Paragraph(", ".join(numbers["lucky_colors"]), styles["body"]),
        Paragraph(", ".join(numbers["lucky_days"]), styles["body"]),
    ]
    table = Table([header, values], colWidths=[5.7 * cm] * 3)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), MID_PURPLE),
        ("BACKGROUND", (0, 1), (-1, 1), DARK_PURPLE),
        ("GRID", (0, 0), (-1, -1), 0.5, GOLD),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
    ]))
    return table


def _parse_ai_sections(ai_text: str, styles: dict) -> list:
    """Convert AI markdown-ish response to ReportLab paragraphs."""
    elements = []
    for line in ai_text.split("\n"):
        line = line.strip()
        if not line:
            elements.append(Spacer(1, 6))
        elif line.startswith("## "):
            elements.append(Spacer(1, 10))
            elements.append(Paragraph(line[3:], styles["section_header"]))
            elements.append(HRFlowable(width="100%", thickness=0.5, color=GOLD, spaceAfter=6))
        elif line.startswith("# "):
            elements.append(Paragraph(line[2:], styles["section_header"]))
        else:
            elements.append(Paragraph(line, styles["body"]))
    return elements


def generate_pdf(report_data: dict) -> bytes:
    """
    Generate a premium PDF from the report data dict.
    report_data keys: full_name, dob, gender, country, numbers, ai_response, generated_at
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=1.5 * cm,
        rightMargin=1.5 * cm,
        topMargin=4.5 * cm,
        bottomMargin=2.5 * cm,
        onFirstPage=_draw_background,
        onLaterPages=_draw_background,
    )

    styles = _styles()
    story = []

    # ── Header ──────────────────────────────────────────────
    story.append(Paragraph("✦ AI NUMEROLOGY ✦", styles["title"]))
    story.append(Paragraph("Your Personal Cosmic Reading", styles["subtitle"]))
    story.append(Spacer(1, 0.4 * cm))
    story.append(HRFlowable(width="100%", thickness=1, color=GOLD, spaceAfter=12))

    # ── Personal Info ────────────────────────────────────────
    info_data = [
        [
            Paragraph(f"<b>Name:</b> {report_data['full_name']}", styles["body"]),
            Paragraph(f"<b>DOB:</b> {report_data['dob']}", styles["body"]),
        ],
        [
            Paragraph(f"<b>Gender:</b> {report_data['gender'].title()}", styles["body"]),
            Paragraph(f"<b>Country:</b> {report_data['country']}", styles["body"]),
        ],
        [
            Paragraph(f"<b>Generated:</b> {report_data['generated_at']}", styles["body"]),
            Paragraph("", styles["body"]),
        ],
    ]
    info_table = Table(info_data, colWidths=[9 * cm, 8 * cm])
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), DARK_PURPLE),
        ("BOX", (0, 0), (-1, -1), 0.5, GOLD),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 0.5 * cm))

    # ── Core Numbers ─────────────────────────────────────────
    story.append(Paragraph("◈ Core Numerology Numbers", styles["section_header"]))
    story.append(_number_table(report_data["numbers"], styles))
    story.append(Spacer(1, 0.4 * cm))

    # ── Number Meanings ──────────────────────────────────────
    story.append(Paragraph("◈ Number Meanings", styles["section_header"]))
    for key, meaning in report_data["numbers"]["meanings"].items():
        label = key.replace("_", " ").title()
        value = report_data["numbers"].get(key, "")
        story.append(
            Paragraph(f"<b>{label} ({value}):</b> {meaning}", styles["body"])
        )
    story.append(Spacer(1, 0.4 * cm))

    # ── Lucky Section ────────────────────────────────────────
    story.append(Paragraph("◈ Lucky Attributes", styles["section_header"]))
    story.append(_lucky_table(report_data["numbers"], styles))
    story.append(Spacer(1, 0.5 * cm))

    # ── AI Interpretation ────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=1, color=GOLD, spaceBefore=8, spaceAfter=8))
    story.append(Paragraph("◈ AI Numerology Reading", styles["section_header"]))
    story.extend(_parse_ai_sections(report_data.get("ai_response", ""), styles))

    doc.build(story)
    return buffer.getvalue()
